#!/usr/bin/env bash
# Installs a `clock` command into ~/.local/bin that launches clock.py
# from this repository. Re-running the script is safe (overwrites wrapper).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
WRAPPER="${BIN_DIR}/clock"

# Required files in the repo
for f in clock.py alarm.mp3 start.mp3; do
    if [[ ! -f "${REPO_DIR}/${f}" ]]; then
        echo "error: missing ${f} in ${REPO_DIR}" >&2
        exit 1
    fi
done

# Hard dependency
if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 not found on PATH" >&2
    exit 1
fi

# Soft dependencies — warn but don't block. Color only when stderr is a tty.
if [[ -t 2 ]]; then YELLOW=$'\033[1;33m'; RESET=$'\033[0m'; else YELLOW=""; RESET=""; fi
command -v mpv         >/dev/null 2>&1 || echo "${YELLOW}warning:${RESET} mpv not found — alarm/start sounds will be silent" >&2
command -v notify-send >/dev/null 2>&1 || echo "${YELLOW}warning:${RESET} notify-send not found — desktop notifications disabled" >&2

mkdir -p "${BIN_DIR}"
chmod +x "${REPO_DIR}/clock.py"

cat > "${WRAPPER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by ${REPO_DIR}/install.sh — do not edit by hand.
exec python3 "${REPO_DIR}/clock.py" "\$@"
EOF
chmod +x "${WRAPPER}"

echo "installed: ${WRAPPER} -> ${REPO_DIR}/clock.py"

case ":${PATH}:" in
    *":${BIN_DIR}:"*)
        ;;
    *)
        echo
        echo "note: ${BIN_DIR} is not on your PATH."
        echo "      add this to ~/.zshrc (or ~/.bashrc):"
        echo "          export PATH=\"\$HOME/.local/bin:\$PATH\""
        ;;
esac
